# Generated by Django 5.2.2 on 2025-06-14 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atten_app', '0002_qrcodesession_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('startime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('date', models.DateField()),
                ('totalStu', models.IntegerField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Atten_app.teacher')),
            ],
        ),
    ]
