# Generated by Django 5.2.2 on 2025-06-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atten_app', '0004_rename_endtime_classsession_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(default='BScCIT', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.CharField(default='3rd Year', max_length=50),
            preserve_default=False,
        ),
    ]
