# Generated by Django 5.2.2 on 2025-06-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atten_app', '0006_studentalert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentalert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
