# Generated by Django 5.2.2 on 2025-06-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atten_app', '0007_alter_studentalert_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentalert',
            name='type',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('success', 'Success')], default='info', max_length=20),
        ),
    ]
