# Generated by Django 5.2.2 on 2025-08-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atten_app', '0009_teacher_department_teacher_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='students',
            field=models.ManyToManyField(related_name='class_sessions', to='Atten_app.student'),
        ),
    ]
