# Generated by Django 5.2.2 on 2025-08-08 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atten_app', '0010_classsession_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classsession',
            name='students',
        ),
    ]
