# Generated by Django 5.2.2 on 2025-09-16 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atten_app', '0012_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='Atten_app.student'),
        ),
    ]
