# Generated by Django 5.2.2 on 2025-10-06 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atten_app', '0013_parent_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('sender', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('announcement', 'Announcement'), ('event', 'Event'), ('academic', 'Academic'), ('alert', 'Alert')], default='announcement', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('priority', models.CharField(default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='Atten_app.parent')),
            ],
        ),
    ]
